app = "gate-dz-bot-final"
primary_region = "cdg"

[build]
  builder = "paketobuildpacks/builder:base"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    type = "requests"
    hard_limit = 250
    soft_limit = 200
